import Image from "next/image";
import { site } from "@/lib/site";

export default function Hero() {
  return (
    <section className="hero">
      <Image
        className="hero__photo"
        src="/images/hero-photo.jpg"
        alt=""
        fill
        priority
        sizes="100vw"
      />
      <div className="hero__scrim" />
      <div className="hero__content">
        <p className="hero__tagline">{site.tagline}</p>
        <h1 className="hero__title">
          Sail through your emotions, with harmony of four strings
          <br />
          Sara Matovic
        </h1>
        <p className="hero__sub">{site.subtitle}</p>
      </div>
      <a className="hero__scroll" href="#about" aria-label="Scroll to about section">
        {/* Animated WebP generated by `npm run process:violin-key`; unoptimized so
            Next serves the animation as-is instead of flattening it. */}
        <Image
          className="hero__scroll-icon"
          src="/images/violin-key.webp"
          alt=""
          width={40}
          height={40}
          unoptimized
        />
        <span className="hero__scroll-line" />
      </a>
    </section>
  );
}
